In [3]:
import numpy
import pandas as pd
import scipy

In [11]:
df = pd.read_csv('music_data.txt', header=None)
lat_lon = df[[116, 117]]
lat_lon.columns = ['Latitude', 'Longitude']

      Latitude  Longitude
0       -15.75     -47.95
1        14.91     -23.51
2        12.65      -8.00
3         9.03      38.74
4        34.03      -6.85
5        12.65      -8.00
6        12.65      -8.00
7        14.66     -17.41
8        52.50      -0.12
9        41.26      69.21
10       41.26      69.21
11       41.90      12.48
12       28.61      77.20
13       33.66      73.16
14       54.68      25.31
15       44.41      26.10
16       44.41      26.10
17       52.50      -0.12
18       44.41      26.10
19       44.41      26.10
20       44.41      26.10
21       44.41      26.10
22       44.41      26.10
23       44.41      26.10
24       44.41      26.10
25       44.41      26.10
26       36.70       3.21
27       36.70       3.21
28        9.03      38.74
29       39.91      32.83
...        ...        ...
1029     41.90      12.48
1030     41.90      12.48
1031     41.90      12.48
1032     38.00      23.71
1033     38.00      23.71
1034     38.00      23.71
1035     38.00      23.71
1036    -15.75     -47.95
1037    -15.75     -47.95
1038    -15.75     -47.95
1039     14.91     -23.51
1040     14.91     -23.51
1041     14.91     -23.51
1042     41.26      69.21
1043     41.26      69.21
1044     41.26      69.21
1045    -35.30     149.12
1046     35.70     139.71
1047     17.25     -88.76
1048     52.50      -0.12
1049     52.50      -0.12
1050     52.50      -0.12
1051     41.71      44.78
1052     41.71      44.78
1053     -6.17      35.74
1054     -6.17      35.74
1055     11.55     104.91
1056     41.33      19.80
1057     54.68      25.31
1058     54.68      25.31

[1059 rows x 2 columns]